### ISSUE TITLE
Remove extra " on --tf-vars in Jenkins

### ISSUE THREAD

**Issue by ddimitrioglo** [MitocGroup/recink#105]

**Comment by eistrati** [comment]
I came across below issue. Please fix it asap.

```
$ recink run terraform -vv --tf-vars="access_key=${AWS_ACCES_KEY_ID},secret_key=${AWS_SECRET_ACCESS_KEY}"
Initialize components registry in /Volumes/Data/Users/eugene/.recink/generic/registry.json


message: Cannot read property 'trim' of undefined
stack: 
  - TypeError: Cannot read property 'trim' of undefined
  -     at opts.map.forEach.item (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/recink/bin/commands/run/generic.js:66:37)
  -     at Array.forEach (native)
  -     at optionsToObject (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/recink/bin/commands/run/generic.js:64:33)
  -     at transformConfig (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/recink/bin/commands/run/generic.js:79:18)
  -     at recink.configureExtend.then.config (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/recink/bin/commands/run/generic.js:177:25)
```

**Comment by AlexandrUrita** [comment]
After publish recink issue is still reproducible:
initial parameters:
![screen shot 2017-12-15 at 16 01 13](https://user-images.githubusercontent.com/27765884/34045428-81ad293a-e1b1-11e7-8684-c89406da2ccc.png)
output parameters:
![screen shot 2017-12-15 at 16 01 13](https://user-images.githubusercontent.com/27765884/34045439-8b3428be-e1b1-11e7-8d4d-4e31f58b9b43.png)

**Comment by AlexandrUrita** [comment]
After reinstall recink & recink-terraform globally issue was resolved:
![screen shot 2017-12-15 at 18 26 40](https://user-images.githubusercontent.com/27765884/34051014-ae2681fa-e1c5-11e7-9e2d-08829af52d0d.png)
![screen shot 2017-12-15 at 18 27 00](https://user-images.githubusercontent.com/27765884/34051015-ae430aa0-e1c5-11e7-8adf-165f77fd3e9e.png)

**Comment by eistrati** [comment]
Checked.
