### ISSUE TITLE
Integrate tests runner into run terraform

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#111]

**Comment by avozicov** [comment]
Test Status:
- unit tests and e2e tests are successfully executed with `recink run terraform` command if specified conditions (from the following task https://github.com/MitocGroup/recink/issues/110) are met 

Note :
- there are still use cases to discuss which are described in the following comment https://github.com/MitocGroup/recink/issues/110#issuecomment-360475306

**Comment by eistrati** [comment]
Checked.
