### ISSUE TITLE
Destroy doesn't work for recink run terraform

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#123]
Reference: http://jenkins.mitocgroup.com/job/Eistrati_Terraform_Demo/59/console

```
20:32:02 Error: Command failed: /mnt/data/jenkins/jobs/Eistrati_Terraform_Demo/workspace/bin/terraform show -no-color /mnt/data/jenkins/jobs/Eistrati_Terraform_Demo/workspace/ec2/.resource/terraform.tfstate
20:32:02 Error loading file: open /mnt/data/jenkins/jobs/Eistrati_Terraform_Demo/workspace/ec2/.resource/terraform.tfstate: no such file or directory
```

**Comment by ddimitrioglo** [comment]
https://github.com/MitocGroup/recink/pull/119/files#diff-7af29ce75da2e28462399f1ce89b3604R309

@eistrati take a look please

**Comment by eistrati** [comment]
@ddimitrioglo https://github.com/MitocGroup/recink/pull/119/files#diff-7af29ce75da2e28462399f1ce89b3604R309 ;)

**Comment by ddimitrioglo** [comment]
@eistrati what does it mean? can not see the difference.

**Comment by eistrati** [comment]
@ddimitrioglo It means that in order to run `terraform destroy`, you need to pass exactly the same parameters as in case of `terraform apply`. Therefore we need to pull the state to identify if tfstate is remote or local. Does this make sense?

**Comment by ddimitrioglo** [comment]
I think we have to do this before `terraform destroy` not after, what do you think?

**Comment by avozicov** [comment]
Test **Passed**
Acceptance Criteria:
- Resource should be successfully destroyed when running `recink run terraform` command with the `destroy` option set to `true` and there should be no errors during command execution
- Changes for the `destroy` functionality in recink should not affect `plan` and `apply` expected behavior

**Comment by eistrati** [comment]
Checked.
