### ISSUE TITLE
Checker of version is not working

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/recink#124]
Steps to reproduce:
1. Setup on local recink with changes on branch issue_107
2. Download on local terraform-demo
3. Run command with parameter recink run terraform -s cache --tf-workspace="test"

Expected result: version checker should be workable

Actual result: version control is not working. higher version on terraform-demo leads to:
[TERRAFORM]
 
### `ec2` skipped executing `terraform workspace`

Reason - "Please use version 0.11.0 (or higher) to leverage "terraform workspace"." ...

![screen shot 2018-01-22 at 12 55 24](https://user-images.githubusercontent.com/27765884/35217341-8e77210e-ff73-11e7-8160-ec4e335d6644.png)

**Comment by AlexandrUrita** [comment]
Also method on line 522 is not working. Should be:

**Comment by AlexandrUrita** [comment]
Issue is still reproducible:
![screen shot 2018-01-22 at 14 57 00](https://user-images.githubusercontent.com/27765884/35221926-bb81a5c8-ff84-11e7-90ac-e43dd60f9e57.png)

**Comment by AlexandrUrita** [comment]
Issue is still reproducible:
<img width="607" alt="screen shot 2018-01-23 at 12 53 05" src="https://user-images.githubusercontent.com/27765884/35272484-02a693fa-003e-11e8-92b8-cdbd0140501e.png">

However I changes version to lower on terraform-demo and workspace worked:
![screen shot 2018-01-23 at 12 56 04](https://user-images.githubusercontent.com/27765884/35273304-cdc031a2-0040-11e8-976f-858e8afd14f4.png)
<img width="654" alt="screen shot 2018-01-23 at 12 53 14" src="https://user-images.githubusercontent.com/27765884/35273317-d4e15bf0-0040-11e8-865e-ebed6e37de0c.png">

Also after running terraform --tf-workspace command I didn't saw any notification which workspace we are using. run with -vv:

**Comment by eistrati** [comment]
Checked.
