### ISSUE TITLE
Add an option to define test target by providing full test-file name in test path

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#128]
Expected result:
- When specifying test target under test config there should be an option to trigger test execution based on full test-file name, instead of placing the file into a directory 

e.x. 
```rds_restore:
  root: './rds_restore'
  terraform:
    version: 0.11.0
    plan: false
    apply: false
    destroy: false
    test:
      mapping: './tests/mapping.json'            
      plan: './tests/unit/resource-name.spec.js' .- expected to run only specified unit test  
      apply: './tests/e2e/resource-name.e2e.js'```- expected to run only specified e2e test

**Comment by avozicov** [comment]
I would suggest a minor improvement for the following implementation.

There is an use case when test path validation is still applied for both test types (unit and e2e) even when execution for one of them is set to false or skipped 

 Steps to reproduce and required configuration:
1. Set `terraform plan` to `false`
2. Set `terraform apply` to `true` 
3. Define an `invalid path` for unit test component
4. Define a `valid path` for e2e test component 
5. Run `recink run terraform`

_Actual behavior:_
- Test execution for e2e scripts is aborted with the path validation error for unit tests 
(even if unit test is aborted by the pre-defined config)

_Expected improvement:_
- Decouple path validation for unit test and e2e test components to make tests suites independent  
- Do not skip particular test type execution if the ignored tests contains invalid path 
- Apply validation only for tests which is not ignored by pre-defined config 

@eugene @ddimitrioglo 
I would suggest to keep the "qa/review" status for the following ticket till we review and discuss the following improvement

**Comment by ddimitrioglo** [comment]
@avozicov Fixed

**Comment by ddimitrioglo** [comment]
@avozicov updates are available in branch issue_116

**Comment by avozicov** [comment]
Test **Passed**
based on the acceptance criteria defined in the comments above

**Comment by eistrati** [comment]
Checked.
