### ISSUE TITLE
Add user friendly message in case invalid test path is defined under test configuration

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#129]
Expected result:
- In case when an invalid test path is defined under test configuration there should be a console message about missing test files in the provided directory 

e.x.
```rds_restore:
  root: './rds_restore'
  terraform:
    version: 0.11.0
    plan: false
    apply: false
    destroy: false
    test:
      mapping: './tests/mapping.json'
      plan: './tests/unit/invalid-test-dir/resources/' - validate the following path for unit tests 
      apply: './tests/e2e/invalid-test-dir/resources.' - validate the following path for e2e tests

**Comment by avozicov** [comment]
Test **Passed**
Acceptance Criteria:
- Path validation should be implemented when running tests with `recink run terraform command` and in case if invalid path has been provided in config - user friendly message is expected to be displayed in console

**Comment by eistrati** [comment]
Checked.
