### ISSUE TITLE
Analyze if snyk.io component should be implemented

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/reCInk#14]
Reference: https://snyk.io

**Comment by AlexanderC** [comment]
It could be integrated by using the following package https://www.npmjs.com/package/snyk

It doesn't have an documented programmatic API thus we have to reverse engineer the code from:
- https://github.com/snyk/snyk/blob/master/cli/commands/test.js
- https://github.com/snyk/snyk/blob/master/lib/api-token.js
- Use https://www.npmjs.com/package/configstore as user defined config wrapper

Please refer to this issue https://github.com/snyk/snyk/issues/93
