### ISSUE TITLE
Implement recink-cnci component

### ISSUE THREAD

**Issue by ddimitrioglo** [MitocGroup/recink#152]
Goal: Replace post-build task actions to `recink run cnci --sync` in Jenkins

**Comment by avozicov** [comment]
I have configured the following project to test CNCI workflow for this ticket, please do not remove it http://jenkins.mitocgroup.com/job/Avozicov_QA_Test_Repository/

**Comment by avozicov** [comment]
Intermediate status:
- configured git repo
- created and configured Jenkins project 
- call account/create endpoint with required info in request body 

Result:
- Jenkins job did not triggered 

I will debug the following use cases and come back with updates:
- Manually run Jenkins project to check if config is valid 
- Temporarily disable 2Factor authentication for my git account
- Check Lambda which triggers Jenkins with CloudWatch logs

**Comment by avozicov** [comment]
Ok, I resolved issue with Jenkins Project and build (with `recink run-cnci --sync`) finished with success if I trigger it manually.
http://jenkins.mitocgroup.com/job/avozicov_CnciTest/16/console

Now I am facing issue wit triggering Jenkins job by PR from my repo
https://github.com/avozicov/QA-Test-Repository/pulls

Investigating and will be back with updates

**Comment by avozicov** [comment]
Test **Passed**
- Opened PR in test repo which have triggered related Jenkins Project
http://jenkins.mitocgroup.com/job/avozicov_CnciTest/
- Got Success status on Jenkins job
http://jenkins.mitocgroup.com/job/avozicov_CnciTest/19/console
- Got comment on PR with execution status
https://github.com/avozicov/QA-Test-Repository/pull/4#issuecomment-384936796

**Comment by eistrati** [comment]
Checked.
