### ISSUE TITLE
Recink execution fails when there are no e2e test assets 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#48]
_Expected result:_
- There should no errors and execution should not be aborted 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-07-25 at 15 42 52" src="https://user-images.githubusercontent.com/12330493/28572701-cf65226c-7150-11e7-806c-def7af43d8dd.png">

**Comment by AlexanderC** [comment]
This happens when test syntax is not valid or no tests inside matched assets.
