### ISSUE TITLE
Travis build is failed with error 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#58]
Details:
- Travis job is failed with the following error:
`TypeError: The super constructor to "inherits" must have a prototype`

Please refer to the link bellow for log and details:
https://travis-ci.com/MitocGroup/atm/jobs/86006425

<img width="1280" alt="screen shot 2017-08-09 at 14 13 31 1" src="https://user-images.githubusercontent.com/12330493/29118976-f2850286-7d0c-11e7-8b61-b6f6717fb8e4.png">

**Comment by AlexanderC** [comment]
Might be related to https://github.com/MitocGroup/recink/issues/43

**Comment by AlexanderC** [comment]
It seems to be an issue with `sandboxed-module` package (works when `-s coverage` option added)

**Comment by avozicov** [comment]
Travis job is **Passed**
Please refer to the following log 
https://travis-ci.com/MitocGroup/atm/jobs/86006425

P.S.
Thank you @AlexanderC for fixing it ;)
