### ISSUE TITLE
Review Travis Failure - The command "./bin/cli.js run e2e" exited with 1

### ISSUE THREAD

**Issue by ivignan** [MitocGroup/recink#68]
Issue Details: https://travis-ci.org/MitocGroup/recink/jobs/283887386#L1639

**Comment by avozicov** [comment]
Test Passed
Acceptance Criteria: 
- there should no be failed jobs for Travis after fix
Please refer to the latest job status
https://travis-ci.org/MitocGroup/recink/jobs/299145663

**Comment by eistrati** [comment]
Checked.
